### ISSUE TITLE
Sometimes, the map changes before the screen fades out

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#101]
You change maps. You should make the map only change when the screen is completely black.

**Comment by definitely-nobody-is-here** [comment]
it does
the map only changes when the screen is completely black

**Comment by maitian352** [comment]
It happened again!
The map changed too late! The map changed while I was fading out.

**Comment by maitian352** [comment]
It happened again!
The map changed too late! The map changed while I was fading out.

**Comment by definitely-nobody-is-here** [comment]
STOP MARKING THINGS AS IN-PROGRESS WHEN THEY ARE NOT BEING WORKED ON. IT MESSES THINGS UP

**Comment by definitely-nobody-is-here** [comment]
I just tested it about 20 times and it hasn't happened once. Either way, it is impossible since the client waits for the map to change before fading out

**Comment by maitian352** [comment]
Still happens. I think what happens is the map changes before the client is completly faded in.

**Comment by definitely-nobody-is-here** [comment]
The client has to be completely faded in since it waits for the animation to finish, then tells the server to teleport.

**Comment by maitian352** [comment]
No it still happens

**Comment by maitian352** [comment]
Maybe the code is broken for detecting when the animaiton is finshed?

**Comment by definitely-nobody-is-here** [comment]
well it uses the built-in css/javascript handler so I can't fix it.
