### ISSUE TITLE
Zooming out causes flashing scrollbars

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#107]
![image](https://user-images.githubusercontent.com/68207888/142736758-95216e8e-0589-41b7-805d-f1a13639ab5c.png)

**Comment by maitian352** [comment]
Zooming in also causes this bug
![image](https://user-images.githubusercontent.com/68207888/142736785-fda167ab-90e1-4ad5-bef9-0e143642c28e.png)

**Comment by definitely-nobody-is-here** [comment]
> Zooming in also causes this bug ![image](https://user-images.githubusercontent.com/68207888/142736785-fda167ab-90e1-4ad5-bef9-0e143642c28e.png)

that is non-reproducable
![image](https://user-images.githubusercontent.com/67865358/142743184-27bf9815-0b54-43bf-b76e-28435c779421.png)

**Comment by definitely-nobody-is-here** [comment]
also, strange that the scroll bars are flashing

**Comment by definitely-nobody-is-here** [comment]
It is because of the chat clipping through because of CSS not being able to handle the placement correctly when zoomed out that far
