### ISSUE TITLE
Can't Sign in

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#112]
I click sign in, and it doesnt work!

![image](https://user-images.githubusercontent.com/68207888/143311998-47d90454-a47e-497e-8b3d-676c2236753c.png)

**Comment by definitely-nobody-is-here** [comment]
You crashed teh server by being stupid. The server doesn't like you.

**Comment by maitian352** [comment]
> You crashed teh server by being stupid. The server doesn't like you.

?
Isn't the correct thing to do is to secure the server so it doesn't crash?
