### ISSUE TITLE
Screen is black

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#113]
I open mountain guarder.
I wait a lot. (I waited 2-3 hours)
I sign in.
This happens.
![image](https://user-images.githubusercontent.com/68207888/143322872-e3b65fa8-e560-4372-8a65-8e6621e969a6.png)

These are the settings
![image](https://user-images.githubusercontent.com/68207888/143322904-3106878a-4700-40e1-a829-b02b4183164d.png)

**Comment by maitian352** [comment]
This also happened.
![image](https://user-images.githubusercontent.com/68207888/143322971-4c90aec1-6cb8-43b3-9794-95c67839ff7a.png)

**Comment by definitely-nobody-is-here** [comment]
#108 
THIS ISSUE WAS ALREADY POSTED
PLEASE CHECK IF THE ISSUE ALREADY EXISTS BEFORE CREATING IT
