### ISSUE TITLE
There can be scrollbars on the canvas

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#114]
![image](https://user-images.githubusercontent.com/68207888/143323082-e5864ab2-2004-4cf1-b95e-986e2c37a7fe.png)

This happened when I opened my inventory and started dragging an item. I used [I] to close the inventory, while the dragging item stayed. They I moved my mouse to the bottom of the screen and this happened.

**Comment by definitely-nobody-is-here** [comment]
#107
