### ISSUE TITLE
Dragging?

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#118]
I think I dragged on the tooltip. Not sure, but I know I was dragging bottom-right.
![image](https://user-images.githubusercontent.com/68207888/143456182-e3346fe6-61d2-4bed-9528-c1f19f8802ad.png)

**Comment by maitian352** [comment]
Yes, this happens when you drag on the tooltip.

**Comment by maitian352** [comment]
This might be chat-related, as I was selecting the chat.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/143459547-841701d2-fce1-48b3-b0b3-ae176fa63d72.png)
This is what I did. I started selecting where the red arrow is, and dragged it all the way to the cyan arrow. Then I moved my mouse outside the chat box, which caused the selection to turn into this.

**Comment by definitely-nobody-is-here** [comment]
you can't drag the tooltip. mouseEvents is set to none

**Comment by definitely-nobody-is-here** [comment]
just in case, I added the noSelect tag to prevent selection of the tooltip and drag images

**Comment by maitian352** [comment]
This is something with the chat and the inventory.

**Comment by maitian352** [comment]
> ![image](https://user-images.githubusercontent.com/68207888/143459547-841701d2-fce1-48b3-b0b3-ae176fa63d72.png) This is what I did. I started selecting where the red arrow is, and dragged it all the way to the cyan arrow. Then I moved my mouse outside the chat box, which caused the selection to turn into this.

This is how I created this glitch.

**Comment by maitian352** [comment]
Sorry, the tutorial is incorrect. This is the correct version.
![image](https://user-images.githubusercontent.com/68207888/143480102-dd13c1a6-29cc-4ca9-8b9a-8472b888dec4.png)
First, position the inventory above the chat. Start dragging from the cyan arrow, and drag to the red arrow. While dragging, open the inventory. You can now let go of the mouse. Now, dragging items produces this glitch.

**Comment by maitian352** [comment]
Sorry, the tutorial is incorrect. This is the correct version.
![image](https://user-images.githubusercontent.com/68207888/143480102-dd13c1a6-29cc-4ca9-8b9a-8472b888dec4.png)
First, position the inventory above the chat. Start dragging from the cyan arrow, and drag to the red arrow. While dragging, open the inventory. You can now let go of the mouse. Now, dragging items produces this glitch.
