### ISSUE TITLE
I deleted an item somehow

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#120]
![image](https://user-images.githubusercontent.com/68207888/143456640-4d1db583-87db-465a-99bb-35756af930e4.png)
I was trying to switch my sword with my bow, so I could see if the sword attack was still there even though I was holding a bow, and somehow this happened. I was dragging by bow, while attacking. I dropped it on the sword, and then this happened.

**Comment by maitian352** [comment]
Nevermind it's still there, its just a client bug. Still a bug though.
![image](https://user-images.githubusercontent.com/68207888/143456856-62d5c0f9-73ca-4a80-b171-a0f7cf54095a.png)

I started dragging on the slot again and the bow reappeared.

**Comment by definitely-nobody-is-here** [comment]
what

**Comment by maitian352** [comment]
I dragged an item, and quickly clicked again right after the item switched,
