### ISSUE TITLE
Dumb Monsters

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#121]
The monsters don't go around the trees, they just get stuck there.
![image](https://user-images.githubusercontent.com/68207888/143459896-cdf0f7f8-fe60-4e7a-a17e-82ef63bef485.png)

**Comment by definitely-nobody-is-here** [comment]
going around trees require them to go into a nomonster region, which they avoid crossing into.

**Comment by maitian352** [comment]
They should evolve to climb over the trees.
