### ISSUE TITLE
VULNERABILITY - Debug allows for viewing of passwords

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/Mountain_Guarder#124]
**Describe the bug**
A player with debug can see other players password because it is stored in the player object.

**Expected behavior**
Passwords should not be stored!

**Screenshots**
![image](https://user-images.githubusercontent.com/67865358/143496564-c88e7c93-e595-42eb-8664-d2697c1f41cc.png)

**Environment**
 - Browser any
 - Version v0.5.4

**Logs**
Will not make tutorial on how to see people's passwords...

**Comment by maitian352** [comment]
oof

**Comment by maitian352** [comment]
please make a tutorial

**Comment by Suvanth-Erranki** [comment]
tutorial requested.

**Comment by definitely-nobody-is-here** [comment]
You use the ingame debug console (requires administrator privileges), and use s.findPlayer('player name here').creds.password

This has been patched and you can no longer use administrator privileges to see passwords.

**Comment by definitely-nobody-is-here** [comment]
This isn't on the changelog since this can only be done by 3 people.
