### ISSUE TITLE
Errors in chat

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#129]
I created a new account
![image](https://user-images.githubusercontent.com/68207888/143775427-2b4b4590-21cc-47d0-9f39-139453d11bc2.png)

**Comment by definitely-nobody-is-here** [comment]
thats normal

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/143775495-1046b8ae-c44d-4d81-9e77-fafe7683e30b.png)
NO INVENTORY!!!!

**Comment by definitely-nobody-is-here** [comment]
oh

**Comment by definitely-nobody-is-here** [comment]
rejoin

**Comment by maitian352** [comment]
but bad and annoying

**Comment by definitely-nobody-is-here** [comment]
This is actually a duplicate of #90
