### ISSUE TITLE
Birds can hit me through the trees.

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#131]
![image](https://user-images.githubusercontent.com/68207888/144712981-bc13fa81-7638-4f40-a43b-6d6d598931f6.png)

**Comment by definitely-nobody-is-here** [comment]
It went between the gap.

**Comment by maitian352** [comment]
> It went between the gap.

How come my arrows can't go between the gap? How come they go through the gap and then disappear if I am further away from the trees?

**Comment by definitely-nobody-is-here** [comment]
it hits the branches and can only go so far before it hits the ground
