### ISSUE TITLE
Chunk borders move slightly when player accelerates

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#132]
I couldn't get a screenshot but you can try yourself.

**Comment by definitely-nobody-is-here** [comment]
They do not have interpolation, debug shows the position on the server. The client smooths out the transitions but on the server the hitboxes do not change between update ticks

**Comment by maitian352** [comment]
No, like the chunk borders vibrate when you are moving.

**Comment by definitely-nobody-is-here** [comment]
it is accurate to how they are on the server, the client has interpolation and is inaccurate

**Comment by maitian352** [comment]
Well make it accurate on the client and fix this bug.

**Comment by definitely-nobody-is-here** [comment]
> Well make it accurate on the client and fix this bug.

It's accurate to how it is on the server, that's what debug does. It shows what's going on on the server. If the client were accurate to what was going on in the server you would be stuck with a painful 20 fps
