### ISSUE TITLE
Add a filter for the chat

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#133]
[Redacted]

Some messages may not be appropriate.

**Comment by maitian352** [comment]
WHY IS IT REDACTED?????

**Comment by maitian352** [comment]
bruh

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/145711953-a13a58a4-6542-49d2-b4af-9fef5dac5ed4.png)
lol
doesnt work

**Comment by maitian352** [comment]
Still Works
![image](https://user-images.githubusercontent.com/68207888/146444828-fbc58a04-3da3-4331-9ea5-9eca316f8327.png)

**Comment by definitely-nobody-is-here** [comment]
I can’t create every possible way to bypass the restrictions I might have to manually delete them
