### ISSUE TITLE
I cant sign in

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#138]
![image](https://user-images.githubusercontent.com/68207888/144747077-65cd34ee-3ed0-44ad-8b6f-cd884c39bd7c.png)
No errors in the console either.

**Comment by maitian352** [comment]
I spammed the sign in button, then when it didn't work, i left the tab. I came back to find this:
![image](https://user-images.githubusercontent.com/68207888/144747155-649a7b05-2d27-4adb-b600-0d390907ae7f.png)

**Comment by definitely-nobody-is-here** [comment]
Duplicate of #136
