### ISSUE TITLE
Enhancement: Change server logs to be EST

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#140]
![image](https://user-images.githubusercontent.com/68207888/144752424-77d4d6c4-8d69-47d8-8096-cadf966ca51d.png)
Its pretty easy to change, and makes reading logs easier.

**Comment by definitely-nobody-is-here** [comment]
This is is because the heroku servers are not located in the EST zone

**Comment by definitely-nobody-is-here** [comment]
Logs are now all recorded in UTC

**Comment by maitian352** [comment]
> This is is because the heroku servers are not located in the EST zone

I change meadow guarder server logs to est. It makes them easier to read.
