### ISSUE TITLE
You can bypass the chat filter

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#144]
It's easy, you can just type a bad word with spaces between every letter.

**Comment by definitely-nobody-is-here** [comment]
fine im gonna remove spaces and make them invalid characters

**Comment by definitely-nobody-is-here** [comment]
instead of just cleaning the message now the filter blocks it entirely.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/147524665-b42c22bf-d805-4ba7-8da6-3daa1337c094.png)
Doesnt work.

**Comment by definitely-nobody-is-here** [comment]
shut up

**Comment by definitely-nobody-is-here** [comment]
do you want me to get a contractor or something to do this?

**Comment by maitian352** [comment]
Yes.
