### ISSUE TITLE
Monster Circling is broken

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#145]
![image](https://user-images.githubusercontent.com/68207888/146652078-a3a7162f-7946-44bb-9f02-9b9f0205abba.png)
The monster is trying to pathfind into the tree?

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/146660049-576c3c24-461e-42b1-8897-86a234b41639.png)

**Comment by maitian352** [comment]
Now the monster isn't moving.
![image](https://user-images.githubusercontent.com/68207888/147840833-10d0fa47-729c-4883-b4f3-2945cf9922d6.png)

**Comment by definitely-nobody-is-here** [comment]
It's running away or something but it can't find a place to run away

**Comment by definitely-nobody-is-here** [comment]
This is a visual glitch, the monster does not actually try and circle into a collision (the key indicators show that the monster does not try and walk into a collision)

**Comment by definitely-nobody-is-here** [comment]
Issue Fixed in v0.9.0
