### ISSUE TITLE
When you create an account, you cant log on, you have to reload

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#147]
![image](https://user-images.githubusercontent.com/68207888/147298769-ff53c683-02c2-49ed-adc1-f4981207d808.png)

**Comment by definitely-nobody-is-here** [comment]
wrong. It works. I just signed in after signing up
![image](https://user-images.githubusercontent.com/67865358/147362080-a1362e97-21f4-41af-ade4-ca29529d8e47.png)
You can see the loading screen and the sign up message at the same time.
