### ISSUE TITLE
Monster dumb?

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#148]
Why is it not attacking me? I have debug open and there is no red ring.
![image](https://user-images.githubusercontent.com/68207888/147299071-9ff965ae-f855-4850-8a76-ba3fd9152f96.png)

**Comment by maitian352** [comment]
Seriously...
![image](https://user-images.githubusercontent.com/68207888/147299088-aeb1d1b8-dcab-4e3c-8176-b2984d725919.png)

**Comment by maitian352** [comment]
My projectiles are not homing on them.

**Comment by definitely-nobody-is-here** [comment]
this is a known bug. At gridx=0 things stop working

**Comment by definitely-nobody-is-here** [comment]
Duplicate of #142

**Comment by maitian352** [comment]
No, like every monster in the bottom is not working.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/147695025-90571af5-3e6b-4f7b-931b-c08901743fc6.png)
