### ISSUE TITLE
Why is the tree in the bridge

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#150]
![image](https://user-images.githubusercontent.com/68207888/147299217-8bf335b3-bae7-483a-aca8-0733878d708e.png)

**Comment by definitely-nobody-is-here** [comment]
oops

**Comment by definitely-nobody-is-here** [comment]
it has been bushed lol
![image](https://user-images.githubusercontent.com/67865358/147361918-96714526-0005-4065-b0e5-6f342c82208b.png)
