### ISSUE TITLE
Settings are broken, pressing \ changes the switch but it does not change the text

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#151]
![image](https://user-images.githubusercontent.com/68207888/147299254-deefe5ce-55e5-48e0-b3b7-387743e4d630.png)
![image](https://user-images.githubusercontent.com/68207888/147299257-f38fdff6-c23e-45f7-8ed8-5e522431b6e5.png)

**Comment by definitely-nobody-is-here** [comment]
ok wierd
