### ISSUE TITLE
BUG - I randomly lost half of my items

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#152]
LETS GO DELETING ITEMS!!!!!!
![image](https://user-images.githubusercontent.com/68207888/147299333-db21c667-d315-4277-967e-fbb826d9b64e.png)

![image](https://user-images.githubusercontent.com/68207888/147299325-6f0ffd97-9f1e-49ae-825c-7020e0144589.png)
![image](https://user-images.githubusercontent.com/68207888/147299327-1726b410-9d17-410c-b3b7-c7dd727ad50e.png)

**Comment by definitely-nobody-is-here** [comment]
ok what

**Comment by definitely-nobody-is-here** [comment]
are you sure you didn't have a half inventory of items and then got a bunch of items?

**Comment by maitian352** [comment]
I am sure. Tianmu even saw this! What was happening was I filled up my inventory, then presses "log off" in the top left. When I logged back on, I lost half of my items.

**Comment by maitian352** [comment]
It seems like the first time you log off this happens.

**Comment by definitely-nobody-is-here** [comment]
how wierd

**Comment by definitely-nobody-is-here** [comment]
I think it's a bug where you can only have 1 of each item. I don't know why.

**Comment by definitely-nobody-is-here** [comment]
I filled my inventory with one item, left, and when i came back I only had 1

**Comment by definitely-nobody-is-here** [comment]
It is because all of the item slots are linked through all players because the global template was modified and every item was actually a reference to one item.
