### ISSUE TITLE
Two staffs???

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#153]
![image](https://user-images.githubusercontent.com/68207888/147299372-e72f7a62-c303-451d-a2b9-9dab7c5f75f5.png)

**Comment by definitely-nobody-is-here** [comment]
that's impossible. How did you do it? I feel like this is a rendering problem and not an inventory problem since the helditem is one object and can only hold one id

**Comment by maitian352** [comment]
Yeah, it might be a rendering bug. I didn't hold two items.

**Comment by definitely-nobody-is-here** [comment]
what did you do to get this result? Is it reproducable?

**Comment by definitely-nobody-is-here** [comment]
If not confirmed within 30 days it will be closed.

**Comment by definitely-nobody-is-here** [comment]
15 days left

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/148870882-bfc97be1-a40c-4739-b940-46ae86bf7333.png)
Just happened again!

**Comment by definitely-nobody-is-here** [comment]
You dropped an item didn't you.

**Comment by definitely-nobody-is-here** [comment]
3 days left to confirm

**Comment by definitely-nobody-is-here** [comment]
This hasn't been confirmed. The issue will be closed and marked as invalid.
