### ISSUE TITLE
Spamming causes item duplication

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#154]
Spam on a slot, and this happens
![image](https://user-images.githubusercontent.com/68207888/147299419-df002fae-bde7-4916-a3d2-f145e14152d5.png)

**Comment by definitely-nobody-is-here** [comment]
but it only happens on client

**Comment by definitely-nobody-is-here** [comment]
how?

**Comment by maitian352** [comment]
I just spam a lot.
It may also help to run 1000 other applications to lag your computer.

**Comment by definitely-nobody-is-here** [comment]
I've been spamming with slow download/upload speeds
hasn't been working.
