### ISSUE TITLE
Npc walks into wall

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#155]
![image](https://user-images.githubusercontent.com/68207888/147299628-a32295d9-5f08-416b-9fc8-36229e5c3d9c.png)
Bob is tyring to walk into the WALL

**Comment by definitely-nobody-is-here** [comment]
yes we know

**Comment by definitely-nobody-is-here** [comment]
ah, I made a typo. I wrote i when I should have written j
