### ISSUE TITLE
Insane lag when moving and shooting with weapon

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#157]
I used the christmas2021 weapon. Its server lag, and as I walked into a cherry bomb my walking slowed down.

**Comment by definitely-nobody-is-here** [comment]
never happened to me

**Comment by definitely-nobody-is-here** [comment]
Nope. Never happens. Never at all. Not on the Heroku server or testing server. Probably your internet speed or ping

**Comment by maitian352** [comment]
IT LAGGED!!!

**Comment by definitely-nobody-is-here** [comment]
shut up it didn't
