### ISSUE TITLE
SUGGESTION - Item Stealage

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#158]
If someone kills a monster, other people can steal the items even if they did not contribute to the kill.

**Comment by definitely-nobody-is-here** [comment]
so some people can't pick up items? that doesn't make sense. Just pick up the item before them

**Comment by maitian352** [comment]
not equity

**Comment by definitely-nobody-is-here** [comment]
so the person who stole ur item is selfish...

**Comment by maitian352** [comment]
No, you are not giving every person an equal chance. If you can click faster, you will get the items.

**Comment by definitely-nobody-is-here** [comment]
sounds like a skill issue

**Comment by maitian352** [comment]
> sounds like a skill issue

im making a hack that auto pickups items

so i can steal items

and so you have to fix this

**Comment by definitely-nobody-is-here** [comment]
im gonna make it impossible for you to pick up items
