### ISSUE TITLE
BUG - You can be kicked for socket emit dos because of a lag spike

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#159]
MAJOR BUG

**Comment by definitely-nobody-is-here** [comment]
It's not possible to prevent lagspikes or even detect them reliably. Instead I'll just raise the limit to 200 messages/second.

**Comment by definitely-nobody-is-here** [comment]
You know what, you fix it.

**Comment by maitian352** [comment]
`socket.on('lagSpike')`
easy

**Comment by definitely-nobody-is-here** [comment]
I don't see this being very reliable even if it is implemented. It would cause problems where people could fake lag and DOS the server.
