### ISSUE TITLE
Monsters can follow you into Snowy Outpost

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#16]
![image](https://user-images.githubusercontent.com/68207888/133007605-852975a2-5cfe-4837-b6fb-bd03e1dd976b.png)
they are not supposted to

**Comment by definitely-nobody-is-here** [comment]
this is because you provoked them by attacking. This is intentional.

**Comment by maitian352** [comment]
not fair
