### ISSUE TITLE
BUG - Christmas 2020 (1) does not target snowball?

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#163]
![image](https://user-images.githubusercontent.com/68207888/147713538-b29d16b0-094d-4c22-a4ee-266a4f188382.png)
Its not working.

**Comment by maitian352** [comment]
No homing projectiles target it.

**Comment by definitely-nobody-is-here** [comment]
They are targeting them. It works.

**Comment by maitian352** [comment]
No, its just this one snowball. This also happens many times and is reproducable. Maybe its because i didn't aggro the snowball? Or something to do with spawning animation.

**Comment by definitely-nobody-is-here** [comment]
I tested this multiple times and it did not happen ONCE.

**Comment by maitian352** [comment]
It's like only this one snowball.

**Comment by maitian352** [comment]
Happened again!
![image](https://user-images.githubusercontent.com/68207888/147770227-c985be75-f09e-448b-a3a0-bc972a30c3cc.png)

**Comment by maitian352** [comment]
You have to make sure the monster doesnt aggro you and doesnt move.

**Comment by maitian352** [comment]
Once i aggro the monster, projectiles start homing.

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147773720-9076d901-40b4-46fa-98d8-3eb10255f43d.png)
this is the code for homing. There is no check for whether the monster is aggroed or not.

**Comment by definitely-nobody-is-here** [comment]
It is not because the monster is not aggroed. It will still target monsters that are not aggroed.
![image](https://user-images.githubusercontent.com/67865358/147774067-9ae6eee0-7d8f-45e0-9bdb-1aba2223800d.png)
However, if the monster is inactive it will not target it.

**Comment by definitely-nobody-is-here** [comment]
It has to do with the monster spawning

**Comment by definitely-nobody-is-here** [comment]
When a monster is spawned, the gridx is 0 until it becomes active.

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147774471-7af7cfcf-4d88-48ae-8f18-4d814627c068.png)
This snowball will be inactive until I approach (0, 0)
