### ISSUE TITLE
BUG - Item clipping through tree

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#164]
![image](https://user-images.githubusercontent.com/68207888/147713616-f79afbdc-1c42-4ee6-9298-e0590aa3461a.png)

**Comment by maitian352** [comment]
If you say "intentional", what it actually means is that you don't feel like fixing it.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149606125-05c05d8f-6c1e-48dc-bb0c-51bfb9d51beb.png)
Still goes inside collisions.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149606136-26b65f22-9391-461c-a11c-717b1816e30b.png)

**Comment by definitely-nobody-is-here** [comment]
I forgot to add the code to monster drops and I made a typo.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149841926-60cc326e-4ece-4286-a872-c5a128bc81c2.png)
Not fixed.

**Comment by definitely-nobody-is-here** [comment]
Apparently, I'm good at making typos.
