### ISSUE TITLE
BUG - typing / in chat gives command not found undefined

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#165]

**Comment by definitely-nobody-is-here** [comment]
because you gave a command of undefined

**Comment by maitian352** [comment]
It should say like (No empty command!) or something

**Comment by definitely-nobody-is-here** [comment]
but you entered a command that is undefined

**Comment by maitian352** [comment]
I entered a command of empty

**Comment by maitian352** [comment]
can you please fix it? Its not that hard to fix.
