### ISSUE TITLE
BUG - Monster Stuck

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#167]
There was a monster stuck in the top right corner. Unfortunately I was using titanium staff and killed it, but here is the drop for proof.
![image](https://user-images.githubusercontent.com/68207888/147713855-bf55acb9-92c3-43a0-b233-df870ea53d12.png)

**Comment by definitely-nobody-is-here** [comment]
What was the path? There is not enough information to fix this.

**Comment by maitian352** [comment]
It was just going up and right.

**Comment by definitely-nobody-is-here** [comment]
Not enough information to confirm
