### ISSUE TITLE
item drops are not balanced and too insane

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#168]

**Comment by definitely-nobody-is-here** [comment]
how? I just balanced them

**Comment by definitely-nobody-is-here** [comment]
The drop chances range from 15 to 9

**Comment by definitely-nobody-is-here** [comment]
It turns out the drop chance scale should be logarithmic since it is relative to the other items in the drop list

**Comment by maitian352** [comment]
I already have 20 titanium staffs, and it is the best weapon. The drop chance is like 1.5 times higher but titanium staff is like 5 times better than wooden sword.

**Comment by definitely-nobody-is-here** [comment]
Technically this was fixed, it just wasn't in the changelogs.
