### ISSUE TITLE
BUG - if you pick up items with your inventory full, throw out some items, you cant pick up items anymore

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#171]
**Describe the bug**
A clear and concise description of what the bug does.

**To Reproduce**
2. Do '...'
3. Go here: '...'
4. See this: '...'

**Expected behavior**

**Screenshots**

**Environment**
 - Browser [e.g. Chrome 90, Safari, Edge]
 - Version [e.g. v0.4.3]

**Logs**
If applicable, place as many event logs as possible. Logs include log.txt, the server console, and client console(s).

**Comment by definitely-nobody-is-here** [comment]
you didn't fill out the template

**Comment by definitely-nobody-is-here** [comment]
Go fill out the template and try again
