### ISSUE TITLE
BUG - You lose 10 resistance when Seasons Yeeting is in your offhand

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#173]
Offhand items are not supposted to affect you.

**Comment by definitely-nobody-is-here** [comment]
You know I have fixed this before you even posted this bug.

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/147840958-bfb94bd6-ef3b-4fa6-80df-46fa14c9f7bc.png)
I then told you I fixed it.
