### ISSUE TITLE
BUG - SampIeprovider(sp) keeps spamming

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#174]
It's really annoying, even with notifications off. I dont know if there are real messages in the mountain guarder discord server or not.
![image](https://user-images.githubusercontent.com/68207888/147838096-8113c6dd-7972-4cf9-9bfd-ce1c4fd44379.png)

**Comment by definitely-nobody-is-here** [comment]
They're real.

**Comment by definitely-nobody-is-here** [comment]
Also, it's the spam channel. Mute it. You won't get pinged and you wont see it as unread until you click on it.
