### ISSUE TITLE
Fence goes above my head

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#177]
![image](https://user-images.githubusercontent.com/68207888/147840842-e2b26110-351f-4cfa-be75-2dc9b453684e.png)

**Comment by definitely-nobody-is-here** [comment]
There's a dead bush there now.

**Comment by maitian352** [comment]
No, the fence is above my head.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149255591-c07e36cd-57dc-462a-b417-4a1d79a08910.png)
Not fixed.

**Comment by definitely-nobody-is-here** [comment]
I can't add more layers, I can't move it to any other layers. The only thing I can do is add a tree.
