### ISSUE TITLE
If you move into the edges of the world so that the camera shifts, and then you move out, your weapon stays in the same angle

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#178]
![image](https://user-images.githubusercontent.com/68207888/147840852-a80022f9-b555-4c64-8d7f-b066a19eb3ed.png)
I couldn't screenshot my cursor, but you can check the mouse position and check my position

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/147842139-a559eb1f-8576-4504-99d4-c7be6f4928e2.png)
Now what?

**Comment by maitian352** [comment]
My cursor is on the right.

**Comment by definitely-nobody-is-here** [comment]
FIRST GITHUB COMMENT ON MOUNTAIN GUARDER IN 2022!!!
also you can't just mark it as in-progress because I'm not working on it.

**Comment by definitely-nobody-is-here** [comment]
This should be closed.
