### ISSUE TITLE
Monsters keep attacking while you are dead

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#18]
they should stop chasing you and stop attacking

![image](https://user-images.githubusercontent.com/68207888/133007661-6900505c-ad3d-425c-92e7-584bc3d85f0b.png)

**Comment by definitely-nobody-is-here** [comment]
They do.

**Comment by maitian352** [comment]
they dont

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/133008215-331e1b95-6efa-4cbb-86f7-5e42e0711d7f.png)

**Comment by maitian352** [comment]
proof
