### ISSUE TITLE
WOO FIRST MOUNTAIN GUARDER ISSUE OF 2022

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#181]
With an actual bug!
![image](https://user-images.githubusercontent.com/68207888/147850385-8215dcb7-9c69-4711-b32c-084fc8802bfa.png)

Can't pick up item.

**Comment by definitely-nobody-is-here** [comment]
Your player has to be close enough to pick up the item.

**Comment by maitian352** [comment]
> Your player has to be close enough to pick up the item.

Then it shouldn't be selected.

**Comment by definitely-nobody-is-here** [comment]
If not confirmed within 30 days it will be closed.

**Comment by definitely-nobody-is-here** [comment]
> > Your player has to be close enough to pick up the item.
> 
> Then it shouldn't be selected.

It isn't anymore. Did you read the changelogs?
