### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#182]
![image](https://user-images.githubusercontent.com/68207888/147850582-3bfbce18-ae37-470b-9a05-57d93f5512e2.png)

**Comment by definitely-nobody-is-here** [comment]
solution: don't stand on the fire.

**Comment by maitian352** [comment]
FIX IT! This is not supposted to happen.

**Comment by definitely-nobody-is-here** [comment]
Yes it is. You stand on fire, you die.
