### ISSUE TITLE
particles in void

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#184]
![image](https://user-images.githubusercontent.com/68207888/148302113-7243bec7-ed47-437f-ae3c-810a013e777c.png)

**Comment by definitely-nobody-is-here** [comment]
If not confirmed within 30 days it will be closed.

**Comment by maitian352** [comment]
This happens if you go out the inn while moving. When you go back, this happens. This happens every time.

**Comment by definitely-nobody-is-here** [comment]
Ah, there are no collisions and you just walk out of the house

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/148868200-b13f0a05-6fad-4086-bd42-16c3727b6c7c.png)
Still happens. I think this happens when you move and teleport, and then quickly teleport back.

**Comment by definitely-nobody-is-here** [comment]
You teleported from there. The particles spawn there. It makes sense.

**Comment by maitian352** [comment]
No, the ones right above my health bar.

**Comment by definitely-nobody-is-here** [comment]
You went from there into the house. It makes sense for particles to spawn there. Or would you like me to add that painful 0.5 second wait back where you can't move?

**Comment by maitian352** [comment]
No, this
![image](https://user-images.githubusercontent.com/68207888/149230873-f35961b9-4053-4040-ac9c-42bd64103353.png)

**Comment by maitian352** [comment]
They don't update if im in the house

**Comment by definitely-nobody-is-here** [comment]
They do.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149256990-06f31153-fe54-4c38-8ef6-55f24c78cb09.png)
they dont

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149842379-1f270967-9f23-488b-b5a8-c5192cb8e019.png)
They don't.

**Comment by definitely-nobody-is-here** [comment]
How. What?

**Comment by maitian352** [comment]
the map also didnt load
