### ISSUE TITLE
Monster invisible at negative indexes

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#185]
Idk what happened
projectiles also turned invisible
i dont know how to reproduce

**Comment by definitely-nobody-is-here** [comment]
I can't fix this if it can't be confirmed. If not confirmed within 30 days it will be closed.

**Comment by maitian352** [comment]
This has happened 10+ times to me.

**Comment by definitely-nobody-is-here** [comment]
It's never happened to me and there is no proof.

**Comment by maitian352** [comment]
projectiles do this too
i just go to the left side of the map

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/148464334-bfa2b8fa-f2ac-4655-95bd-6333d2ef418c.png)
what

**Comment by definitely-nobody-is-here** [comment]
So the entities are deemed to be out of render distance...

**Comment by definitely-nobody-is-here** [comment]
socket.io was deleting the negative indexes

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/148668220-8614a769-2683-46e7-969b-9bbc112347dd.png)
WHAT

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/148668368-90bef1af-af3c-4f49-ae15-5184b3f993c9.png)

**Comment by definitely-nobody-is-here** [comment]
It was fine for me. Also that's a different bug. I think you're looking for #195

**Comment by definitely-nobody-is-here** [comment]
No it doesn't.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/150444549-1bb6be36-0b18-4695-b7e0-d9979e620c17.png)
Still happens.

**Comment by definitely-nobody-is-here** [comment]
That's a loading issue, I can't fix it. The server is sending the packets because you can see it in debug. It's a client issue because sometimes your computer sucks and can't keep the images correctly loaded. I can't fix it.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/150444933-0ed99680-774f-42cc-81bb-c33c69da6961.png)

**Comment by maitian352** [comment]
> That's a loading issue, I can't fix it. The server is sending the packets because you can see it in debug. It's a client issue because sometimes your computer sucks and can't keep the images correctly loaded. I can't fix it.

Then how come this doesnt happen to meadow guarder which has like 1000 image files but it happens consistantly to mountain guarder?

**Comment by definitely-nobody-is-here** [comment]
*consistently

**Comment by maitian352** [comment]
Additionally, particles also don't display. There is one chunk that is the right of Snowy outpost that displays, but going more right makes it bork.

**Comment by definitely-nobody-is-here** [comment]
It's not invisible at negative indexes. It hasn't happened to me in so long it might was well be fake.

**Comment by maitian352** [comment]
It happens to me and I would have been able to get more information if you didnt turn the page into a rickroll that DOESNT WORK

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/150445256-95476f9b-9ca7-40a6-9178-b562f1811db5.png)

**Comment by definitely-nobody-is-here** [comment]
Wrong bug. If it's not at a negative index it's not this bug.
