### ISSUE TITLE
I cant move down here

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#188]
![image](https://user-images.githubusercontent.com/68207888/148302550-181b64b3-4928-44e4-94a5-251325b7c3a5.png)

**Comment by definitely-nobody-is-here** [comment]
I don't see anything wrong.

**Comment by maitian352** [comment]
There is empty land, and I cant move into it because a collision is blocking me.

**Comment by definitely-nobody-is-here** [comment]
If I let you you would complain about the player being too close to the edge of the water.

**Comment by maitian352** [comment]
then?

**Comment by definitely-nobody-is-here** [comment]
I would change it back and you would reopen this issue.
