### ISSUE TITLE
SUGGESTION - No player animatinos

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#19]
![image](https://user-images.githubusercontent.com/68207888/133007686-1d8527e4-4101-4cdc-b106-d726478d541c.png)

big bug

**Comment by definitely-nobody-is-here** [comment]
It's intentional. It's not a bug. A bug is when it behaves not according to plan. Animations were never added.

**Comment by definitely-nobody-is-here** [comment]
This should be a suggestion

**Comment by maitian352** [comment]
bgcfuhqji
