### ISSUE TITLE
Monster Pathfinding is broken

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#192]
![image](https://user-images.githubusercontent.com/68207888/148668044-0d2ed059-f943-40e1-96a4-33c6632cb223.png)
The snowball is stuck here
![image](https://user-images.githubusercontent.com/68207888/148668057-2dbce197-2c55-4707-88a3-daa6dd83c0cb.png)

**Comment by definitely-nobody-is-here** [comment]
It's circling you but it has nowhere to circle. It doesn't want to go closer to you.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/148668145-621f1f02-fe2a-4927-8b75-4f40e562ec83.png)

What about this???

**Comment by definitely-nobody-is-here** [comment]
That's a different bug.

**Comment by definitely-nobody-is-here** [comment]
I think you're looking for #145

**Comment by maitian352** [comment]
That's definitly pathfinding. It was like 10 blocks away.

**Comment by definitely-nobody-is-here** [comment]
I don't have a full screenshot so I can't confirm it, so therefore I can't fix it.
