### ISSUE TITLE
Under the snow???

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#193]
![image](https://user-images.githubusercontent.com/68207888/148668078-921eae94-d0c5-4b13-91a4-67642116c5a3.png)
Top right

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/148668084-2fea2a29-8ea5-4fa6-a85e-c6f66575f026.png)

**Comment by definitely-nobody-is-here** [comment]
shut up i haven't figured it out yet.

**Comment by definitely-nobody-is-here** [comment]
I intentionally left it there because you kept telling me to commit but I wasn't finished
