### ISSUE TITLE
Cant move left

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#196]
![image](https://user-images.githubusercontent.com/68207888/148668169-18016e0f-92f9-4a63-b8a3-18002f9c90f3.png)

**Comment by definitely-nobody-is-here** [comment]
That's your problem.

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/148668205-ff6acf9c-be86-4acb-b05f-b9ea46584bfd.png)
Your character got caught on this edge. It shouldn't, but it did. Probably a collision issue.

**Comment by definitely-nobody-is-here** [comment]
The player is clipping through because x has priority in the collision checks. If y had priority you could move left, but in a similar setup but vertical you wouldn't be able to.

**Comment by definitely-nobody-is-here** [comment]
Actually, it's caused by an incorrect number in the collision entity generation
