### ISSUE TITLE
In the water and under bridge

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#199]
![image](https://user-images.githubusercontent.com/68207888/148668209-20d83a02-3dff-438b-bca7-bfb03abd93b0.png)

**Comment by definitely-nobody-is-here** [comment]
PLEASE fill out the template so we can reproduce it and don't have to ask how you got there

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/148668280-ad52d0d4-e24d-4ad9-b099-e433da7d480e.png)

**Comment by maitian352** [comment]
just walk into the water

**Comment by definitely-nobody-is-here** [comment]
It didn't work

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/148668346-b09c20d4-1a62-4cb4-b4be-825d22d39d0f.png)
AAAAAAAA

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/148668476-aeac8e94-19e8-41e7-b452-4f6a6ae80db8.png)
It's fine? This is on a testing server...

**Comment by maitian352** [comment]
It happens sometimes.

**Comment by definitely-nobody-is-here** [comment]
It didn't work again on the heroku server.

**Comment by definitely-nobody-is-here** [comment]
Either way I changed the collision layout so it shouldn't happen again.

**Comment by maitian352** [comment]
I believe you have to go inside the house and come back out.
