### ISSUE TITLE
You can do the auto move glitch

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#20]
Hold w, then press ctrl + t

**Comment by definitely-nobody-is-here** [comment]
that closed my tab.

**Comment by definitely-nobody-is-here** [comment]
Fixed for the most part, automove still works when clicking the taskbar but that can't be fixed.

**Comment by maitian352** [comment]
> Fixed for the most part, automove still works when clicking the taskbar but that can't be fixed.

This also happens in Meadow Guarder, and can't be fixed.
