### ISSUE TITLE
When you join the map is black sometimes

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#204]
It takes time to load/draw

**Comment by definitely-nobody-is-here** [comment]
True. It takes a bit to render the maps at first.

**Comment by maitian352** [comment]
Still happens.

**Comment by definitely-nobody-is-here** [comment]
No it doesn't. It renders then it shows. If it does then ten eyed one is not pixelated

**Comment by maitian352** [comment]
It is black. You can even see it in the particle in void issue.

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149843491-19d67f4c-c906-497d-80d5-97808d0237e6.png)
