### ISSUE TITLE
Tooltip still shows even though i dropped the item using q

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#210]
![image](https://user-images.githubusercontent.com/68207888/149255369-e71544e4-a8a6-4e0f-8af5-70bfcb99eb4a.png)

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149841889-7d351bd8-ced3-4b41-b581-2c2af9316e63.png)
Not fixed. Just drop the item and then move your mouse.

**Comment by definitely-nobody-is-here** [comment]
I literally added code that hides the tooltip when you drop an item

**Comment by definitely-nobody-is-here** [comment]
I just tested it. I had my hand off my mouse, and pressed q. the tooltip hid.

**Comment by maitian352** [comment]
No, you have to move your mouse by a tiny amount.

**Comment by maitian352** [comment]
No, you have to move your mouse by a tiny amount.
