### ISSUE TITLE
Sometimes select doesnt show up

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#211]
![image](https://user-images.githubusercontent.com/68207888/149255469-b8495f5a-e472-45ab-ab78-f4e660d953f9.png)

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/149622384-6b78b430-17c9-40aa-9a55-fafe69982a4c.png)
ok this is wierd

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/163461027-c8bd59d0-f9e1-40ea-aa62-95915569cdda.png)
...
this is local server

**Comment by definitely-nobody-is-here** [comment]
Nevermind I had use controller on

**Comment by definitely-nobody-is-here** [comment]
Ah, a typo.
