### ISSUE TITLE
Invalid layer with monsters

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#213]
![image](https://user-images.githubusercontent.com/68207888/149255860-eee3908f-263f-4895-8785-ea75ad3c7cf3.png)

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/149256100-137ef1ac-482b-4bc5-86b4-5ab2dbcb1917.png)
They just go down the staircase and break

**Comment by definitely-nobody-is-here** [comment]
Duplicate of #197

**Comment by definitely-nobody-is-here** [comment]
I think I fixed the monsters having invalid layers? They can cross the bridge fine now.

**Comment by maitian352** [comment]
No, is monsters going down stairs.

**Comment by definitely-nobody-is-here** [comment]
The bridge has stairs

**Comment by maitian352** [comment]
On the bridge can monsters go through collisions?

**Comment by definitely-nobody-is-here** [comment]
no

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/150449183-f2ac78fd-9232-4e77-a0b2-f8be6fc035ef.png)
hmmmmmm

**Comment by definitely-nobody-is-here** [comment]
Issue Fixed in v0.9.0
