### ISSUE TITLE
Under rock

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#214]
![image](https://user-images.githubusercontent.com/68207888/149255913-bfe58199-17b3-47c5-bc03-4fd4cc46966d.png)

**Comment by definitely-nobody-is-here** [comment]
I FIXED THIS YERSTERDAY

**Comment by maitian352** [comment]
theres no done label lol

**Comment by spsquared** [comment]
ok fine i added one
