### ISSUE TITLE
Cant pickup coin

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#230]
![image](https://user-images.githubusercontent.com/68207888/164326914-3286ad43-4c34-4caf-8017-13a845f55ea8.png)

**Comment by definitely-nobody-is-here** [comment]
Right click on it.

**Comment by definitely-nobody-is-here** [comment]
There isn't enough information. What have you tried?

**Comment by maitian352** [comment]
Right clicking. If i go to the top right then the yellow coin pops up, but i still cannot pick it up.

**Comment by definitely-nobody-is-here** [comment]
is you inventory full?

**Comment by maitian352** [comment]
No
