### ISSUE TITLE
Server Tick Timed Out

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#231]
![image](https://user-images.githubusercontent.com/68207888/164327108-14bcb3da-b4bb-4f11-aa3c-5ee38297d050.png)

**Comment by definitely-nobody-is-here** [comment]
Why don't you try to fix it? I can't seem to find the problem.

**Comment by definitely-nobody-is-here** [comment]
v0.11.0 Replaced the physics, should be fixed now.
