### ISSUE TITLE
Snow bird unbalanced

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#232]
They are nearly impossible to kill with the starting wooden bow and end up filling up all the spawners.

**Comment by definitely-nobody-is-here** [comment]
They're supposed to be hard. Don't kill them until you get better stuff.

**Comment by definitely-nobody-is-here** [comment]
You can go north and stay closer to the Snowy Outpost if you don't want to encounter any Snow Birds

**Comment by maitian352** [comment]
> They're supposed to be hard. Don't kill them until you get better stuff.

You cant get better stuff because there are too many snow birds so you cant kill any monsters to get better stuff.

**Comment by maitian352** [comment]
> You can go north and stay closer to the Snowy Outpost if you don't want to encounter any Snow Birds

yeah right
![image](https://user-images.githubusercontent.com/68207888/168448127-b57ffa25-322a-4848-876c-32cdf86eaf2a.png)
