### ISSUE TITLE
monster and items on invalid layer

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#239]

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/168482409-4680953e-5905-4101-bb7b-5baa684c599b.png)
spawner issues

**Comment by definitely-nobody-is-here** [comment]
There's missing collisions for layer 3 in this area
![image](https://user-images.githubusercontent.com/67865358/168482504-497cc703-b407-4cf6-b1bd-fb45fa24d28f.png)
They've been filled in and this shouldn't happen anymore.

**Comment by definitely-nobody-is-here** [comment]
Fixed in v0.11.0.
