### ISSUE TITLE
unplayable with tiny screen

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#248]
![image](https://user-images.githubusercontent.com/68207888/185134079-0e7e4d13-e9ec-4fcc-933d-fb1848c691fb.png)

**Comment by definitely-nobody-is-here** [comment]
The game will obviously be unplayable on a tiny screen. Try doing anything on a tiny screen. Pretty much everything is unusable on tiny screens.

**Comment by maitian352** [comment]
> The game will obviously be unplayable on a tiny screen. Try doing anything on a tiny screen. Pretty much everything is unusable on tiny screens.

except for ocean guarder
