### ISSUE TITLE
thing

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#25]
where is the player?

![image](https://user-images.githubusercontent.com/68207888/133007899-f8800215-b33c-4f9b-8606-8be6ceb67ea7.png)

can you see?

the player is underneath the region display

hard to see

fix please

**Comment by definitely-nobody-is-here** [comment]
it also happens in meadowgaurder.

**Comment by maitian352** [comment]
so? that doesnt just make it not a bug
