### ISSUE TITLE
birds snipe you

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#27]
The bird can't even see you and pathfinding doesnt work and yet it knows the exact direciton to fire ninja stars

![image](https://user-images.githubusercontent.com/68207888/133007963-4c08d2e8-f7e3-43e5-94cf-4e83f27b02a0.png)

**Comment by definitely-nobody-is-here** [comment]
so what. you're bad.

**Comment by maitian352** [comment]
unrealistic
