### ISSUE TITLE
invisible monsteres

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#272]
![image](https://user-images.githubusercontent.com/68207888/211099558-4a81441c-a9b3-41ab-bfca-eb606051d837.png)

idk what

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/211099645-c370f369-64f7-4f8b-8029-12c36e14ee41.png)

**Comment by definitely-nobody-is-here** [comment]
this is #271
