### ISSUE TITLE
bug warping with lodestone while selling itme crashes the server

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#273]
buh

**Comment by definitely-nobody-is-here** [comment]
![image](https://user-images.githubusercontent.com/67865358/211107403-9b723234-0e43-47f4-b1c5-cc58010ceb69.png)

**Comment by definitely-nobody-is-here** [comment]
It tries to close the sell shop and crashes

**Comment by definitely-nobody-is-here** [comment]
I forgot to set `player.shop` to `self` in the sell shop code
