### ISSUE TITLE
invincibility glitch

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#275]
1. use lodestone
2. while teleporting talk to sell itme npc but stay in dialogue
3. walk to sp cave
4. click sell itmes
5. invincible but you can still attack

**Comment by definitely-nobody-is-here** [comment]
You can no longer interact with NPCs while teleporting.

**Comment by definitely-nobody-is-here** [comment]
Forgot to tag it in the patch notes... oops
