### ISSUE TITLE
Sneek Peak - New SNOW BIRD

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/Mountain_Guarder#3]
Yes, Mountain Guarder will have the old Meadow Guarder birds, along with new variations!
![image](https://user-images.githubusercontent.com/67865358/130508093-2d71cb2b-e8de-487d-bf0d-aa04828e089e.png)

**Comment by maitian352** [comment]
you should have a snowstorm bird and a rock bird. The Snowstorm Bird could be like Red Bird.

**Comment by definitely-nobody-is-here** [comment]
no.
