### ISSUE TITLE
Region display takes way too long to fade out

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#36]
I think i've never seen it fade out before

If you really want it to never fade out, put it somewhere else like the top right corner or something.

![image](https://user-images.githubusercontent.com/68207888/133008575-b9474e97-e775-433d-8548-2295bfb90f7b.png)

**Comment by maitian352** [comment]
oops wrong screenshot

**Comment by definitely-nobody-is-here** [comment]
It has a 5 second timer

**Comment by maitian352** [comment]
well it doesnt work

it hasn't faded out for me yet

**Comment by maitian352** [comment]
ah, i see

i somehow found a rare bug

now it works

**Comment by maitian352** [comment]
but still, 5 seconds seems too long
