### ISSUE TITLE
Player Drawing is inefficient

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#37]
![image](https://user-images.githubusercontent.com/68207888/133008864-acd7f956-807b-4769-9b29-73288b381132.png)

LOOK

35%

**Comment by definitely-nobody-is-here** [comment]
fine. you find a better way to tint the iamge.

**Comment by maitian352** [comment]
just render it once?

**Comment by maitian352** [comment]
tint
