### ISSUE TITLE
BIRD SNIPES ME FROM UNRENDERED CHUNKS!!!!!!!

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#38]
![image](https://user-images.githubusercontent.com/68207888/133008955-99cd4d98-862c-4f63-8b37-8e8feb01ca8b.png)

what

you can see the ninja stars

no bird though

**Comment by definitely-nobody-is-here** [comment]
The bird isn't rendered but it's still there.

**Comment by maitian352** [comment]
but still bug

its not supposted to happen
