### ISSUE TITLE
you can walk outside the world

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#39]
![image](https://user-images.githubusercontent.com/68207888/133009100-eb69918d-8477-488e-8c6c-c9fd104e260b.png)

**Comment by definitely-nobody-is-here** [comment]
how? FILL IN THE TEMPLATE IT'S THERE FOR A REASON!

**Comment by definitely-nobody-is-here** [comment]
Intentional. There will be a transporter later.
