### ISSUE TITLE
Teleporter is slanted

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#53]
![image](https://user-images.githubusercontent.com/68207888/135753309-9834e6ac-e0ab-4a93-94d3-2ad5fca85e47.png)

**Comment by definitely-nobody-is-here** [comment]
that's normal.

**Comment by maitian352** [comment]
YOU HAVETO FIXIT

ITS ABUG

**Comment by maitian352** [comment]
still feels weird
