### ISSUE TITLE
Sign in twice

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#72]
![image](https://user-images.githubusercontent.com/68207888/137632306-77ae7117-c9f2-4eeb-9fe9-2fe25e3bf276.png)

**Comment by maitian352** [comment]
i created an account

**Comment by definitely-nobody-is-here** [comment]
You cannot create an account that already exists, plus the signing in twice has been fixed in an upcoming update already
