### ISSUE TITLE
BUG - Monsters get stuck in one position when circling

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#73]
![image](https://user-images.githubusercontent.com/68207888/137632362-36d7992a-6715-48de-b762-24346c96a4ad.png)
the snowball is stuck moving like this

**Comment by definitely-nobody-is-here** [comment]
how did you get the path debug? that feature was not added yet

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/145712713-15026d17-2daa-4e6b-8007-8955e1c1316f.png)
This time its just stuck!

**Comment by definitely-nobody-is-here** [comment]
you have cornered it

**Comment by definitely-nobody-is-here** [comment]
it doesn't happen anymore since the pathfinding has been fixed
