### ISSUE TITLE
Sneek Peak - Mountain Guarder Item Creator Tool!

### ISSUE THREAD

**Issue by definitely-nobody-is-here** [definitely-nobody-is-here/Mountain_Guarder#85]
A new tool arises...

The **Mountain Guarder Item Creator Tool** (**MGIC** Tool)! It allows you to create items quickly while previewing it!

![image](https://user-images.githubusercontent.com/67865358/140330403-2d28e585-91f9-462b-825a-cd1f8c55fcdf.png)

You can make weapons, armor, and even custom offhands!

![image](https://user-images.githubusercontent.com/67865358/140330488-535566b5-14be-494e-bf49-36ae597022fc.png) ![image](https://user-images.githubusercontent.com/67865358/140330584-fdf771e8-9b40-4eea-b2c7-a8789f9af3c0.png)

This is only the start, so stay tuned for more!

**Comment by maitian352** [comment]
> A new tool arises...
> 
> The **Mountain Guarder Item Creator Tool** (**MGIC** Tool)! It allows you to create items quickly while previewing it!


not actually that fast

a google sheet is better
