### ISSUE TITLE
this

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#87]
![image](https://user-images.githubusercontent.com/68207888/140626948-694fba0e-2b1c-4103-b4fa-6947600cd856.png)

**Comment by definitely-nobody-is-here** [comment]
intentional

**Comment by maitian352** [comment]
if you close issues with "intentional", can I close issues with "intentional"?

**Comment by maitian352** [comment]
you even add an "invalid" label
