### ISSUE TITLE
Inventory Corruption

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#90]
![image](https://user-images.githubusercontent.com/68207888/141657206-4705b811-8238-47d0-b722-8daa5cae315d.png)

I have no more items.

**Comment by definitely-nobody-is-here** [comment]
It just happened to me too!

**Comment by definitely-nobody-is-here** [comment]
It seems like it's just client side since the server still saves it I probably made a typo
