### ISSUE TITLE
Game is boring

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#96]
There is nothing to do. Even items don't work as my inventory is corrupted. You should add more maps, add a plot, fix the inventory, add Npcs, and add bosses and more interesting monsters.

**Comment by definitely-nobody-is-here** [comment]
check the to-do list

**Comment by maitian352** [comment]
> check the to-do list

I don't get it. You should close this issue when everything in it is fixed.

**Comment by definitely-nobody-is-here** [comment]
there is nothing to fix. it's not broken. if it hasn't been done at all it can't be fixed because it can't exist

**Comment by maitian352** [comment]
Its a suggestion. A suggestion is closed when everything in it is added.
